name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_manylinux2014_x86_64:
    name: Build WasmEdge-image using g++ on manylinux2014_x86_64 platform
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:manylinux2014_x86_64
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build manylinux2014_x86_64 package
      run: |
        yum check-update || true
        yum install -y wget
        curl -s -L -O --remote-name-all https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.bz2
        bzip2 -dc boost_1_75_0.tar.bz2 | tar -xf -
        export PATH="/toolchain/bin:$PATH"
        export CC=gcc
        export CXX=g++
        rm -rf build
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=Off -DBOOST_INCLUDEDIR=./boost_1_75_0/ .
        cmake --build build
        cd build
        tar -zcvf WasmEdge-image.tar.gz include/wasmedge-image.h lib/libwasmedge-image_c.so
        tar Jcvf WasmEdge-image.tar.xz include/wasmedge-image.h lib/libwasmedge-image_c.so
        cd ..
        mv build/WasmEdge-image.tar.gz WasmEdge-image.tar.gz
        mv build/WasmEdge-image.tar.xz WasmEdge-image.tar.xz
        wget https://github.com/second-state/WasmEdge-image/releases/download/0.7.3/ssvm-image-deps-0.7.3-manylinux1_x86_64.tar.gz
        tar -zxvf ssvm-image-deps-0.7.3-manylinux1_x86_64.tar.gz
        tar -zcvf WasmEdge-image-deps.tar.gz libjpeg.so.8.3.0 libpng16.so.16.37.0
        tar Jcvf WasmEdge-image-deps.tar.xz libjpeg.so.8.3.0 libpng16.so.16.37.0
        ls -alF
